# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Deploy static food app to Azure Web App - Vk-food-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8CB8D916F5C24092856809ED8FF67806 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7190D07E1E96438DAEABF971A635D4D7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_16BFCDEF1FC04E15BC0164AA88CB054F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Vk-food-app'
          slot-name: 'Production'
          package: .

          
